Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/psutil/_psosx.py", line 346, in wrapper
    return fun(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/psutil/_common.py", line 480, in wrapper
    raise raise_from(err, None)
          ^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 3, in raise_from
  File "/opt/homebrew/lib/python3.11/site-packages/psutil/_common.py", line 478, in wrapper
    return fun(self)
           ^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/psutil/_psosx.py", line 373, in _get_kinfo_proc
    ret = cext.proc_kinfo_oneshot(self.pid)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ProcessLookupError: [Errno 3] assume no such process (originated from sysctl(kinfo_proc), len == 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/psutil/__init__.py", line 361, in _init
    self.create_time()
  File "/opt/homebrew/lib/python3.11/site-packages/psutil/__init__.py", line 719, in create_time
    self._create_time = self._proc.create_time()
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/psutil/_psosx.py", line 346, in wrapper
    return fun(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/psutil/_psosx.py", line 471, in create_time
    return self._get_kinfo_proc()[kinfo_proc_map['ctime']]
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/psutil/_psosx.py", line 351, in wrapper
    raise NoSuchProcess(self.pid, self._name)
psutil.NoSuchProcess: process no longer exists (pid=46777)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/bin/airflow", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/airflow/__main__.py", line 48, in main
    args.func(args)
  File "/opt/homebrew/lib/python3.11/site-packages/airflow/cli/cli_config.py", line 52, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/airflow/utils/cli.py", line 112, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/airflow/cli/commands/webserver_command.py", line 494, in webserver
    monitor_gunicorn(gunicorn_master_proc.pid)
  File "/opt/homebrew/lib/python3.11/site-packages/airflow/cli/commands/webserver_command.py", line 459, in monitor_gunicorn
    ).start()
      ^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/airflow/cli/commands/webserver_command.py", line 218, in start
    self._check_workers()
  File "/opt/homebrew/lib/python3.11/site-packages/airflow/cli/commands/webserver_command.py", line 264, in _check_workers
    num_workers_running = self._get_num_workers_running()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/airflow/cli/commands/webserver_command.py", line 151, in _get_num_workers_running
    workers = psutil.Process(self.gunicorn_master_proc.pid).children()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/psutil/__init__.py", line 332, in __init__
    self._init(pid)
  File "/opt/homebrew/lib/python3.11/site-packages/psutil/__init__.py", line 373, in _init
    raise NoSuchProcess(pid, msg='process PID not found')
psutil.NoSuchProcess: process PID not found (pid=46777)
